Fix/cross check tasks list
igorlyatskiy/rsschool-app pull request #4
Opened 2022-01-24 16:56 UTC by VladLutskevich

#### 🧑‍⚖️ Pull Request Naming Convention

 - Title should follow [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary)
 - Do not put issue id in title
 - Do not put WIP in title. Use [Draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/) functionality
 - Consider to add `area:*` label(s)

 * [ ] I followed naming convention rules

---

#### 🤔 This is a ...
- [ ] New feature
- [ ] Bug fix
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Test Case
- [ ] Documentation update
- [ ] Other

#### 🔗 Related issue link

_Describe the source of requirement, like related issue link._

#### 💡 Background and solution 

_Describe the big picture of your changes here_

#### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Database migration is added or not needed
- [ ] Documentation is updated/provided or not needed
- [ ] Changes are tested locally

2022-01-26 10:38 UTC, igorlyatskiy requested changes

2022-01-26 10:38 UTC, igorlyatskiy commented on client/src/components/Forms/CourseTaskSelect.tsx
> +        )}
Переписать через .map

2022-01-26 18:14 UTC, igorlyatskiy commented on client/src/components/Forms/CourseTaskSelect.tsx
>    const dataNotSubmitted = dataActive.filter(task => task.id % 2 === 1);
Ты абсолютно уверен, что это работает? Выглядит, будто это id таска, не связанные с сабмитом или не сабмитом

2022-01-28 16:26 UTC, igorlyatskiy approved these changes

2022-01-28 20:36 UTC, KostyaDedulya requested changes

2022-01-28 20:36 UTC, KostyaDedulya commented on client/src/components/Forms/CourseTaskSelect.tsx
> +  data.sort(function (a, b) {
a, b is bad naming

2022-01-28 20:36 UTC, KostyaDedulya commented on client/src/components/Forms/CourseTaskSelect.tsx
> -  const { data, onChange, ...rest } = props;
rest is bad naming

2022-01-28 20:36 UTC, KostyaDedulya commented on client/src/components/Forms/CourseTaskSelect.tsx
>    const selectProps = onChange ? { onChange } : {};
onChange || {}

2022-01-28 20:36 UTC, KostyaDedulya commented on client/src/components/Forms/CourseTaskSelect.tsx
> +    return Date.parse(b.studentEndDate ?? '') - Date.parse(a.studentEndDate ?? '');
NaN === 0 => false
NaN > 0 => false
NaN < 0 => false

2022-01-28 20:36 UTC, KostyaDedulya commented on client/src/components/Forms/CourseTaskSelect.tsx
> +  const dataSubmitted = dataActive.filter(task => task.id % 2 === 0);// hardcode just for testing purposes, not in use now
If only for testing, please remove it

2022-01-28 21:21 UTC, KostyaDedulya commented on client/src/components/Forms/CourseTaskSelect.tsx
> +    return Date.parse(b.studentEndDate ?? '') - Date.parse(a.studentEndDate ?? '');
If you want to get NaN maybe => Date.parse(b?.studentEndDate)

2022-01-31 11:42 UTC, igorlyatskiy approved these changes

2022-01-31 11:43 UTC, merged