Fix/cross check messages
igorlyatskiy/rsschool-app pull request #5
Opened 2022-01-25 19:27 UTC by VladLutskevich

2022-01-26 12:30 UTC, igorlyatskiy approved these changes

2022-01-26 12:30 UTC, igorlyatskiy commented on client/src/components/CrossCheckComments.tsx
> +                        color={j === 0 ? 'green' : 'gray'}
remove it into getColor

2022-01-26 12:30 UTC, igorlyatskiy commented on client/src/components/CrossCheckComments.tsx
> +                          <p style={{ opacity: j === 0 ? '1' : '0.6' }}>
Remove into getOpacity 
`const getOpacity = (j) => return j === 0 ? '1' : '0.6'`

2022-01-26 12:30 UTC, igorlyatskiy commented on client/src/components/CrossCheckComments.tsx
> +                          <p key={k} style={{ opacity: j === 0 ? '1' : '0.6' }}>
same

2022-01-26 12:30 UTC, igorlyatskiy commented on client/src/components/CrossCheckComments.tsx
> +      {comments.map((reviewComment, i) => (
Naming, i is not good

2022-01-26 12:30 UTC, igorlyatskiy commented on client/src/components/CrossCheckComments.tsx
> +                  .map(({ score, comment, dateTime }, j) => (
j? Naming

2022-01-26 12:30 UTC, igorlyatskiy requested changes
Фиксани замечания до пятницы

2022-01-28 16:18 UTC, igorlyatskiy requested changes

2022-01-28 16:18 UTC, igorlyatskiy commented on client/src/components/CrossCheckComments.tsx
> +  const getColor = (j: number) => (j === 0 ? 'green' : 'gray');
Fix naming

2022-01-28 16:18 UTC, igorlyatskiy commented on client/src/components/CrossCheckComments.tsx
> +  const getColor = (j: number) => (j === 0 ? 'green' : 'gray');
commentIndex, not j

2022-01-28 16:27 UTC, igorlyatskiy approved these changes

2022-01-28 16:27 UTC, igorlyatskiy approved these changes

2022-01-28 20:39 UTC, KostyaDedulya requested changes

2022-01-28 20:39 UTC, KostyaDedulya commented on client/src/components/CrossCheckComments.tsx
> +      dateTime: number;
this can be separate type

2022-01-28 20:39 UTC, KostyaDedulya commented on client/src/components/CrossCheckComments.tsx
> +  const getOpacity = (commentIndex: number) => (commentIndex === 0 ? '1' : '0.6');
magic numbers

2022-01-28 20:39 UTC, KostyaDedulya commented on client/src/components/CrossCheckComments.tsx
> +                      <br></br>
<br/>

2022-01-31 10:58 UTC, igorlyatskiy approved these changes

2022-01-31 10:58 UTC, merged