Feature/cross check review constructor
igorlyatskiy/rsschool-app pull request #6
Opened 2022-01-26 11:47 UTC by andreikovna

Add components for creating and downloading to backend Criteria Data for Cross-check.

2022-01-26 14:40 UTC, KostyaDedulya requested changes

2022-01-26 14:40 UTC, KostyaDedulya commented on client/src/modules/crossCheckCriteria/components/EditableTableForCrossCheck.tsx
> +  );
two files

2022-01-27 06:53 UTC, andreikovna commented on client/src/modules/crossCheckCriteria/components/EditableTableForCrossCheck.tsx
> +  );
Разбила на два компонента - таблица и ячейка

2022-01-27 07:01 UTC, KostyaDedulya approved these changes

2022-02-02 11:07 UTC, KostyaDedulya requested changes

2022-02-02 11:07 UTC, KostyaDedulya commented on client/src/components/Schedule/FormEntity.tsx
> +    newCriteria.map((item, index) => (item.index = index));
What is it?

2022-02-02 11:07 UTC, KostyaDedulya commented on client/src/components/Schedule/FormEntity.tsx
> +    newDataCriteria.map((item, index) => (item.index = index));
What is it?

2022-02-02 11:50 UTC, andreikovna commented on client/src/components/Schedule/TableView.tsx
> +              <>
removed it

2022-02-02 11:50 UTC, andreikovna commented on client/src/modules/crossCheckCriteria/components/ModalCrossCheckCriteria.tsx
> +    newCriteria.map((item, index) => (item.index = index));
add new function to avoid double code

2022-02-02 11:53 UTC, KostyaDedulya approved these changes

2022-02-02 20:18 UTC, igorlyatskiy requested changes

2022-02-02 20:18 UTC, igorlyatskiy commented on client/src/modules/crossCheckCriteria/components/ModalCrossCheckCriteria.tsx
> +  if (dataCriteria === undefined) {
Use strict comparisson

2022-02-02 20:18 UTC, igorlyatskiy commented on client/src/modules/crossCheckCriteria/components/ExportJSONButton.tsx
> +    return newData;
`return criteria.map(item => _.omit(item, ['key', 'index'])); `

2022-02-02 20:18 UTC, igorlyatskiy commented on client/src/modules/crossCheckCriteria/components/ExportJSONButton.tsx
> +          download="filename.json"
crossCheckCriteria.json

2022-02-02 20:40 UTC, andreikovna commented on client/src/modules/crossCheckCriteria/components/ExportJSONButton.tsx
> +    return newData;
changed

2022-02-02 20:46 UTC, igorlyatskiy approved these changes

2022-02-02 20:51 UTC, merged